### 계좌 찾기
GET http://localhost:8080/account?user_id=1
Accept: application/json


### 계좌 생성
POST http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "initialBalance": 10000
}
### 계좌 해지
DELETE http://localhost:8080/account
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000009"
}