### 잔액 사용
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber" : "1000000000",
  "amount": 1000
}

### 잔액 사용2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber" : "1000000000",
  "amount": 1000
}


### 잔액 사용 취소
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "39b38f9dcd90438e928ae845cef09b15",
  "accountNumber" : "1000000000",
  "amount": 1000
}

### 거래 정보
GET http://localhost:8080/transaction/e4d1811a8eca4106b7b08a10867f2201
Content-Type: application/json
